services:
  - type: static_site
    name: food-del-frontend
    env: node
    root: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://food-del-backend-2-tho7.onrender.com
